version: '3.9'

services:
  app:
    image: nginx:alpine
    ports:
      - "8000:80"   
    env_file:
      - .env
    volumes:
      - ./app:/usr/share/nginx/html
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
