services:
  vonage-verify:
    image: vonage-verify:latest
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: vonage-verify
    ports:
      - '127.0.0.1:${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - shared_net

networks:
  shared_net:
    external: true